version: '3.8'

services:
  api-gateway:
    image: rogeriofontes/api-gateway
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    deploy:
      mode: replicated
      replicas: 3

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
